site_name: Titans-Vision

theme:
  features:
    - navigation.tabs
  logo: assets/titans.png
  name: material
  palette:
    - scheme: titans-light
      toggle:
        icon: material/weather-night
        name: Modo escuro
    - scheme: titans-dark
      toggle:
        icon: material/weather-sunny
        name: Modo claro

extra_css:
  - stylesheets/extra.css

nav:
  - Sistema de Visão:
      - Introdução: visao/index.md
      - Instalação: visao/1instalar.md
      - Configuração do Campo: visao/2campo.md
      - Segmentação de Cor: visao/3cores.md
      - Configuração de Dados: visao/4dado.md


